---
name: Build
permissions:
  contents: write

on:
  push:
    branches:
      - moonlightvibe-dev
  pull_request:
    branches:
      - master

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    uses: ./.github/workflows/build-moonlightvibe-windows.yml
